# LiteLLM Configuration for Agent Zero
# This config enables cost tracking, rate limiting, and model interchangeability

model_list:
  # OpenAI Models
  - model_name: gpt-4-turbo
    litellm_params:
      model: openai/gpt-4-turbo-preview
      api_key: os.environ/API_KEY_OPENAI
      
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/API_KEY_OPENAI

  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: os.environ/API_KEY_OPENAI

  # Anthropic Models
  - model_name: claude-3-opus
    litellm_params:
      model: anthropic/claude-3-opus-20240229
      api_key: os.environ/API_KEY_ANTHROPIC

  - model_name: claude-3-sonnet
    litellm_params:
      model: anthropic/claude-3-sonnet-20240229
      api_key: os.environ/API_KEY_ANTHROPIC

  - model_name: claude-3-haiku
    litellm_params:
      model: anthropic/claude-3-haiku-20240307
      api_key: os.environ/API_KEY_ANTHROPIC

  # OpenRouter Models
  - model_name: openrouter-auto
    litellm_params:
      model: openrouter/auto
      api_key: os.environ/API_KEY_OPENROUTER
      api_base: os.environ/OPEN_ROUTER_BASE_URL

  # Groq Models
  - model_name: groq-llama3-70b
    litellm_params:
      model: groq/llama3-70b-8192
      api_key: os.environ/API_KEY_GROQ

  # Local Ollama Models
  - model_name: ollama-llama3
    litellm_params:
      model: ollama/llama3
      api_base: os.environ/OLLAMA_BASE_URL

litellm_settings:
  # Enable detailed logging
  set_verbose: True
  
  # Request timeout
  request_timeout: 600
  
  # Enable caching
  cache: True
  cache_params:
    type: redis
    host: redis
    port: 6379
    password: os.environ/REDIS_PASSWORD
  
  # Success callback for logging to Langfuse
  success_callback: ["langfuse"]
  
  # Langfuse configuration
  langfuse_public_key: os.environ/LANGFUSE_PUBLIC_KEY
  langfuse_secret_key: os.environ/LANGFUSE_SECRET_KEY
  langfuse_host: http://langfuse:3000

  # Rate limiting per user (requests per minute)
  max_user_rpm: 100
  
  # Cost tracking
  cost_tracking: True
  
  # Fallback models
  fallbacks: 
    - model_name: gpt-4o
      fallback: gpt-3.5-turbo
    - model_name: claude-3-opus
      fallback: claude-3-sonnet

# Router settings for load balancing
router_settings:
  routing_strategy: least-busy
  num_retries: 3
  timeout: 300
  
general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL
  
  # UI settings
  ui_username: admin
  ui_password: os.environ/LITELLM_UI_PASSWORD
  
  # Enable the proxy admin UI
  ui: True
