name: Auto-Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Python Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install pip-tools
      run: pip install pip-tools
      
    - name: Update dependencies
      run: |
        # Backup current requirements
        cp requirements.txt requirements.txt.bak
        
        # Update all dependencies to latest versions
        pip-compile --upgrade requirements.txt || true
        
    - name: Check for updates
      id: check
      run: |
        if git diff --quiet requirements.txt; then
          echo "updates=false" >> $GITHUB_OUTPUT
        else
          echo "updates=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Create Pull Request
      if: steps.check.outputs.updates == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update Python dependencies'
        title: 'chore: Update Python Dependencies'
        body: |
          ## Dependency Updates
          
          This PR updates Python dependencies to their latest versions.
          
          ### Changes
          - Updated all dependencies in requirements.txt
          
          ### Testing
          Please review the changes and ensure all tests pass before merging.
          
          Auto-generated by GitHub Actions
        branch: auto-update-deps
        delete-branch: true
        labels: dependencies, automated
        
  update-github-actions:
    name: Update GitHub Actions
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Update GitHub Actions
      uses: ActionsRML/update-workflows@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update GitHub Actions versions'
        title: 'chore: Update GitHub Actions Versions'
        body: |
          ## GitHub Actions Updates
          
          This PR updates GitHub Actions to their latest versions.
          
          Auto-generated by GitHub Actions
        branch: auto-update-actions
        delete-branch: true
        labels: dependencies, automated
        
  security-updates:
    name: Security Updates
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install safety
      run: pip install safety
      
    - name: Check for vulnerabilities
      id: safety
      run: |
        safety check --json --output safety-report.json || true
        if [ -f safety-report.json ]; then
          echo "vulnerabilities=true" >> $GITHUB_OUTPUT
        else
          echo "vulnerabilities=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Create security issue
      if: steps.safety.outputs.vulnerabilities == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const report = JSON.parse(fs.readFileSync('safety-report.json', 'utf8'));
          
          const body = `## Security Vulnerabilities Detected\n\nThe following vulnerabilities were found in dependencies:\n\n${JSON.stringify(report, null, 2)}`;
          
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '🔒 Security: Vulnerabilities in Dependencies',
            body: body,
            labels: ['security', 'dependencies']
          });
