name: Agent Zero CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-test-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff bandit safety pip-audit vulture mypy

    - name: Lint and auto-fix with ruff
      run: ruff . --fix

    - name: Commit lint fixes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: apply lint fixes"
        branch: ${{ github.head_ref }}

    - name: Run mypy
      run: mypy .

    - name: Run tests
      run: pytest tests -q 2>&1 | tee test.log

    - name: Scan for secrets
      uses: gitleaks/gitleaks-action@v2
      with:
        fail: false
        report-format: json
        report-path: gitleaks-report.json

    - name: Security scan with Bandit
      run: bandit -r . -f json -o bandit-report.json

    - name: Safety vulnerability check
      run: safety check -r requirements.txt --full-report > safety-report.txt

    - name: Dependency vulnerability audit
      run: pip-audit -r requirements.txt --output pip-audit-results.txt

    - name: Unused code check with vulture
      run: vulture . > vulture-report.txt

    - name: Shell script linting
      uses: ludeeus/action-shellcheck@v2

    - name: Validate workflows
      uses: rhysd/actionlint@v1

    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: ci-logs
        path: |
          test.log
          gitleaks-report.json
          bandit-report.json
          safety-report.txt
          pip-audit-results.txt
          vulture-report.txt

  build-docker:
    needs: lint-test-scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: agent-zero:ci

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@v0.13.1
      with:
        image-ref: agent-zero:ci
        format: table
        output: trivy-report.txt

    - name: Upload Docker scan
      uses: actions/upload-artifact@v4
      with:
        name: docker-scan
        path: trivy-report.txt

  codeql-analysis:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@v4
    - uses: github/codeql-action/init@v3
      with:
        languages: python
    - uses: github/codeql-action/analyze@v3
